import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createState,act,settle,normalize,gpa} from './assets/garden/engine.mjs';
let checks=0;function test(name,fn){fn();checks++;console.log('PASS',name)}
const now=new Date('2026-09-18T10:00:00').getTime();
test('one harvest cannot be claimed twice; inventory can be sold',()=>{let s=createState(now);assert.throws(()=>act(s,{type:'harvest',index:0},now));s=act(s,{type:'water',index:0},now+1000);const due=s.game.plots[0].ready;assert.equal(due,now+45250);assert.throws(()=>act(s,{type:'water',index:0},now+2000));s=act(s,{type:'harvest',index:0},due);assert.equal(s.game.stock.radish,2);assert.throws(()=>act(s,{type:'harvest',index:0},due));s=act(s,{type:'sell',crop:'radish'},due);assert.equal(s.game.coins,52);assert.equal(s.game.stock.radish,0)});
test('seed spending, locked plots and level requirements',()=>{let s=createState(now);const before=structuredClone(s);assert.throws(()=>act(s,{type:'plant',index:3,crop:'radish'},now));assert.deepEqual(s,before);s=act(s,{type:'plant',index:1,crop:'radish'},now);assert.equal(s.game.seeds.radish,3);assert.throws(()=>act(s,{type:'plant',index:1,crop:'radish'},now));assert.throws(()=>act(s,{type:'buySeed',crop:'lychee'},now));s=act(s,{type:'gift'},now);s=act(s,{type:'unlock',index:3},now);assert.equal(s.game.coins,0);assert.equal(s.game.plots[3],null)});
test('daily gifts and quest rewards are one-time, clock rollback cannot reset',()=>{let s=act(createState(now),{type:'gift'},now);assert.throws(()=>act(s,{type:'gift'},now));s=act(s,{type:'plant',index:1,crop:'radish'},now);s=act(s,{type:'quest',id:'plant'},now);assert.throws(()=>act(s,{type:'quest',id:'plant'},now));assert.throws(()=>act(s,{type:'gift'},now-86400000));s=act(s,{type:'gift'},now+86400000);assert.equal(s.game.daily.gift,true)});
test('focus survives reload, early/duplicate claims fail',()=>{let s=act(createState(now),{type:'focusStart',minutes:5},now);s=normalize(JSON.parse(JSON.stringify(s)),now+120000);assert.throws(()=>act(s,{type:'focusClaim'},now+120000));s=act(s,{type:'focusClaim'},now+300000);assert.equal(s.game.stats.minutes,5);assert.equal(s.game.coins,45);assert.throws(()=>act(s,{type:'focusClaim'},now+300000))});
test('offline pet does not die and sleep restores energy',()=>{let s=createState(now);s.game.pet.energy=20;s=act(s,{type:'sleep'},now);s=settle(s,now+3600000);assert.equal(s.game.pet.energy,50);s=settle(s,now+86400000*10);assert.ok(s.game.pet.hunger>=15);assert.ok(s.game.pet.mood>=20);assert.equal(s.game.plots[0].crop,'radish')});
test('todos reward completion only once',()=>{let s=act(createState(now),{type:'todoAdd',id:'task',text:'test'},now);for(let i=0;i<3;i++)s=act(s,{type:'todoToggle',id:'task'},now);assert.equal(s.game.pet.xp,2);assert.equal(s.game.stats.tasks,1)});
test('invalid imports are rejected; unknown root fields are excluded',()=>{assert.throws(()=>normalize({schema:1},now));let s=createState(now);s.game.coins=-1;assert.throws(()=>normalize(s,now));s=createState(now);s.game.plots[0].crop='unknown';assert.throws(()=>normalize(s,now));s=createState(now);s.password='must-not-export';s.game.pet.password='must-not-export';s.semester='2026-09-01';s=normalize(s,now);assert.equal(s.password,undefined);assert.equal(s.game.pet.password,undefined);assert.equal(s.semester,'2026-09-01')});
test('GPA is credit-weighted without score conversion',()=>assert.deepEqual(gpa([{credit:3,point:4},{credit:1,point:2}]),{credits:4,value:3.5}));
test('independent decoration ownership and achievement reward',()=>{let s=createState(now);s=act(s,{type:'decor',id:'flower'},now);assert.equal(s.game.coins,5);s=act(s,{type:'decor',id:'flower'},now);assert.equal(s.game.coins,5);assert.equal(s.game.equipped.length,0);s=act(s,{type:'harvest',index:0},now+60000);s=act(s,{type:'achievement',id:'harvest'},now+60000);assert.equal(s.game.coins,35);assert.throws(()=>act(s,{type:'achievement',id:'harvest'},now+60000))});
const html=readFileSync(new URL('./index.html',import.meta.url),'utf8');test('HTML IDs are unique',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length)});
console.log(`${checks} checks passed`);
